### ISSUE TITLE
Selection behavior in display editor

### ISSUE THREAD

**Issue by georgweiss** [ControlSystemStudio/phoebus#1309]
When selecting multiple objects in the display editor a selection area is drawn. The limits of this bounding box is defined by the lowest and highest coordinates found among the selected items. There is a side effect of this: additional objects within that rectangle cannot be added to the selection using keyboard and mouse in the editor area, user will need to add such selections in the widgets table on the left.

I'd like to understand the rationale of this behavior as it contrast to other applications (e.g. PowerPoint) where the selection is rendered by highlighting only the selected objects, and not the bounding box defined by (some of) them.

**Comment by pavel-ch** [comment]
Adding / Removing object inside selection area is really something which should work, regardless of the implementation (one or more selection box(es)). Right now, removing works but adding not.

**Comment by kasemir** [comment]
Yes, it's based on the 'EDM' idea where the overall selection size is clearly visible, there are easy to grab resize handles (no need to try and hit the exact line to resize). To change the selection of widgets, i.e. to add or remove a widget that's under the tracker outline, you need to use control-click instead of a plain click.
.. Except for some reason that's broken for addition. Control-click will remove a widget from the selection, but not add it (Command-click on Mac since Control-click is already used for context menu on Mac). There's a bug somewhere in the event filter/handler.

**Comment by kasemir** [comment]
Fixed.
The tracker already had 'passClickToWidgets' because of an issue with passing events on to underlying widget. A JavaFX event _filter_ (as opposed to _handler_) simply didn't work, events with Ctrl or Command pressed didn't reach the widgets, so the Tracker did that on its own.
.. but only for widgets in the selection, so those could be de-selected.
Updated to check all widgets, so now you can Ctrl (Command)-click to add as well as remove from selection.

**Comment by pavel-ch** [comment]
Thank you Kay

**Comment by kasemir** [comment]
It's not recursive, yet, so doesn't fully work within for example a 'group'. Will have another update later today.

**Comment by georgweiss** [comment]
Well, not sure what to expect, but I still cannot add a widget inside the "tracker" box. Attached BOB file is an example: if you select (using CMD + click on Mac) buttons 1,2 and 4, then button 3 cannot be added to the selection using CMD + click.

![image](https://user-images.githubusercontent.com/35602960/81593475-cddbeb80-93bf-11ea-808f-5e9558a63d13.png)
[select.bob.zip](https://github.com/ControlSystemStudio/phoebus/files/4611194/select.bob.zip)

**Comment by kasemir** [comment]
Select 1, 2, 3:

![Screen Shot 2020-05-11 at 1 51 45 PM](https://user-images.githubusercontent.com/1932421/81594254-97d24380-938e-11ea-8896-771e32321a26.png)

Command-click on 4 to add it to the selection:
![Screen Shot 2020-05-11 at 1 51 50 PM](https://user-images.githubusercontent.com/1932421/81594302-ade00400-938e-11ea-94d0-00bf3e97cf5b.png)

Cmd-click again on 4, and it's removed from the selection as in the first screenshot.

**Comment by georgweiss** [comment]
I can confirm, thanks @kasemir
